from selenium.webdriver.common.by import By

ACCOUNT_BUTTON_IN_HEADER = (By.XPATH, ".//p[contains(text(), 'Личный Кабинет')]")
EMAIL_FIELD_ON_AUTH_FORM = (By.XPATH, ".//input[@type='text']")
PASSWORD_FIELD_ONAUTH_FORM = (By.XPATH, ".//input[@type='password']")
LOGIN_BUTTON = (By.XPATH, ".//button[contains(text(), 'Войти')]")
ORDER_BUTTON = (By.XPATH, ".//button[contains(text(), 'Оформить заказ')]")
ACCOUNT_BUTTON_IN_MAIN_SECTION = (By.XPATH, ".//section//div//button[contains(text(), 'Войти в аккаунт')]")
REGISTER_ACCOUNT_LINK = (By.XPATH, ".//a[contains(text(), 'Зарегистрироваться')]")
LOGIN_LINK = (By.XPATH, ".//a[starts-with(@href, '/login')]")
FORGOT_PASSWORD_LINK = (By.XPATH, ".//a[starts-with(@href, '/forgot-password')]")
FILLINGS_SECTIONS = (By.XPATH, ".//h2[contains(text(), 'Начинки')]")
SAUCES_SECTION = (By.XPATH, ".//h2[contains(text(), 'Соусы')]")
BREAD_SECTION = (By.XPATH, ".//h2[contains(text(), 'Булки')]")
CONSTRUCTOR_BUTTON = (By.XPATH, ".//p[contains(text(), 'Конструктор')]")
SAVE_BUTTON_IN_ACCOUNT = (By.XPATH, ".//button[contains(text(), 'Сохранить')]")
NAME_FIELD_ON_REGISTRATION_FORM = (By.XPATH, ".//label[text()='Имя']/parent::div/input")
EMAIL_FIELD_ON_REGISTRATION_FORM = (By.XPATH, ".//label[text()='Email']/parent::div/input")
PASSWORD_FIELD_ON_REGISTRATION_FORM = (By.XPATH, ".//input[@type='password']")
REGISTER_ACCOUNT_BUTTON = (By.XPATH, ".//form//button")
HINT_BAD_PASSWORD = (By.XPATH, ".//div[@class='input__container']//p")
EXIT_BUTTON_IN_ACCOUNT = (By.XPATH, ".//button[contains(text(), 'Выход')]")
